config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.11
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/edanya-uma/TsunamiHySEA:
      branch: main
      repo: https://github.com/edanya-uma/TsunamiHySEA
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/edanya-uma/TsunamiHySEA git:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-ecru-tang.sh
        container: qc.acc_shabby-tan-grouse
  QC.Doc:
    repos:
      github.com/edanya-uma/TsunamiHySEA find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.beady-cream-camel.sh
        container: qc.doc_shaky-sepia-spitz
      github.com/edanya-uma/TsunamiHySEA git:
        commands:
        - /usr/bin/env sh .sqa/script.homely-ochre-audemer.sh
        container: qc.doc_muzzy-cinnabar-mole
      github.com/edanya-uma/TsunamiHySEA markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-silver-quetzal.sh
        container: qc.doc_surly-olive-capybara
  QC.Lic:
    repos:
      github.com/edanya-uma/TsunamiHySEA licensee:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-flax-cuscus.sh
        container: qc.lic_stinky-plum-gorilla
  QC.Met:
    repos:
      github.com/edanya-uma/TsunamiHySEA cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-salmon-bullfrog.sh
        container: qc.met_shabby-gamboge-setter
  QC.Ver:
    repos:
      github.com/edanya-uma/TsunamiHySEA get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-lilac-rat.sh
        container: qc.ver_zippy-brown-grouse
timeout: 5400
