config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.11
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/edanya-uma/TsunamiHySEA:
      branch: main
      repo: https://github.com/edanya-uma/TsunamiHySEA
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/edanya-uma/TsunamiHySEA git:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-cardinal-quokka.sh
        container: qc.acc_skinny-wisteria-deer
  QC.Doc:
    repos:
      github.com/edanya-uma/TsunamiHySEA find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-lime-mandrill.sh
        container: qc.doc_fuzzy-viridian-malamute
      github.com/edanya-uma/TsunamiHySEA git:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-burgundy-balinese.sh
        container: qc.doc_baggy-bistre-bonobo
      github.com/edanya-uma/TsunamiHySEA markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-rust-termite.sh
        container: qc.doc_freaky-brown-birman
  QC.Lic:
    repos:
      github.com/edanya-uma/TsunamiHySEA licensee:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-zucchini-rottweiler.sh
        container: qc.lic_scaly-cream-mayfly
  QC.Met:
    repos:
      github.com/edanya-uma/TsunamiHySEA cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-rose-zorse.sh
        container: qc.met_sunny-seashell-eagle
  QC.Ver:
    repos:
      github.com/edanya-uma/TsunamiHySEA get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-amber-newt.sh
        container: qc.ver_lousy-jade-impala
timeout: 5400
