config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.10
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/edanya-uma/TsunamiHySEA:
      branch: v1.0.0
      repo: https://github.com/edanya-uma/TsunamiHySEA
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/edanya-uma/TsunamiHySEA git:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-grey-angelfish.sh
        container: qc.acc_scaly-chestnut-wombat
  QC.Doc:
    repos:
      github.com/edanya-uma/TsunamiHySEA find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-pear-eagle.sh
        container: qc.doc_pasty-denim-toad
      github.com/edanya-uma/TsunamiHySEA git:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-russet-barnacle.sh
        container: qc.doc_lousy-linen-toad
      github.com/edanya-uma/TsunamiHySEA markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-copper-dachshund.sh
        container: qc.doc_frumpy-aqua-chihuahua
  QC.Lic:
    repos:
      github.com/edanya-uma/TsunamiHySEA licensee:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-silver-rat.sh
        container: qc.lic_surly-ochre-ragdoll
  QC.Ver:
    repos:
      github.com/edanya-uma/TsunamiHySEA get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-chestnut-pig.sh
        container: qc.ver_sleazy-fuchsia-newfoundland
timeout: 5400
