config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.10
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/edanya-uma/TsunamiHySEA:
      branch: main
      repo: https://github.com/edanya-uma/TsunamiHySEA
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/edanya-uma/TsunamiHySEA git:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-seashell-termite.sh
        container: qc.acc_gloppy-charcoal-lemur
  QC.Doc:
    repos:
      github.com/edanya-uma/TsunamiHySEA find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-fuchsia-weasel.sh
        container: qc.doc_whiny-lemon-bracke
      github.com/edanya-uma/TsunamiHySEA git:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-blue-anteater.sh
        container: qc.doc_lanky-ochre-lemur
      github.com/edanya-uma/TsunamiHySEA markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-lavender-greyhound.sh
        container: qc.doc_dorky-sapphire-newt
  QC.Lic:
    repos:
      github.com/edanya-uma/TsunamiHySEA licensee:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-thistle-ladybird.sh
        container: qc.lic_snappy-wisteria-snake
  QC.Ver:
    repos:
      github.com/edanya-uma/TsunamiHySEA get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-ecru-flounder.sh
        container: qc.ver_flimsy-aqua-cat
timeout: 5400
