config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.11
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/edanya-uma/TsunamiHySEA:
      branch: main
      repo: https://github.com/edanya-uma/TsunamiHySEA
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/edanya-uma/TsunamiHySEA git:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-plum-markhor.sh
        container: qc.acc_sloppy-aqua-earwig
  QC.Doc:
    repos:
      github.com/edanya-uma/TsunamiHySEA find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-brown-foxhound.sh
        container: qc.doc_flimsy-scarlet-quokka
      github.com/edanya-uma/TsunamiHySEA git:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-aquamarine-ferret.sh
        container: qc.doc_squirrely-plum-badger
      github.com/edanya-uma/TsunamiHySEA markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-grey-monster.sh
        container: qc.doc_jumpy-eggplant-fly
  QC.Lic:
    repos:
      github.com/edanya-uma/TsunamiHySEA licensee:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-wisteria-lizard.sh
        container: qc.lic_greasy-cinnabar-stoat
  QC.Met:
    repos:
      github.com/edanya-uma/TsunamiHySEA cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-magenta-neanderthal.sh
        container: qc.met_tacky-charcoal-seahorse
  QC.Ver:
    repos:
      github.com/edanya-uma/TsunamiHySEA get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-flax-mongrel.sh
        container: qc.ver_hilly-green-moose
timeout: 5400
